# Generated by Django 3.2.13 on 2025-03-10 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_auto_20250310_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='SavedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_workouts', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='workouts.workout')),
            ],
            options={
                'unique_together': {('user', 'workout')},
            },
        ),
    ]
